[package]
name = "token_biu"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "token_biu"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true


[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build",  "anchor-spl/idl-build"]

[dependencies]
anchor-lang = {version = "0.30.1",  features = ["init-if-needed"]}
anchor-spl =  "0.30.1"
anchor-lang-idl = { version = "0.1.1", features = ["convert"] }
pyth-solana-receiver-sdk = "0.4.0"
bs58 = "0.5.0"
solana-security-txt = "1.1.1"
